import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { neobrutalism, } from '@clerk/themes'
import { ThemeProvider } from "@/components/theme-provider";
import QueryProvider from "@/components/query-client";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClerkProvider appearance={{
          variables: {
            colorPrimary: "#DB2777",          // Tailwind pink-600 (vibrant primary)
            colorBackground: "#FABCAC",   // Let gradient show through
            colorText: "#A3004C",             // Deep navy (contrast on light pinks)
            colorInputBackground: "rgba(255,255,255,0.6)", // Frosted glass input
            colorInputText: "#1A2A4F",
            colorDanger: "#E11D48",           // Strong rose red for errors
            colorSuccess: "#FBCFE8",          // Soft pink success (gentle tone)
          },

          theme: [neobrutalism],
        }}>
          <QueryProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              {children}
              <Toaster richColors position="bottom-right" />
            </ThemeProvider>
          </QueryProvider>
        </ClerkProvider>
      </body>
    </html>
  );
}
